{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.component",
    "module": "component-plugin",
    "version": "1.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "component-plugin-1.9.4.jar",
          "url": "component-plugin-1.9.4.jar",
          "size": 42485,
          "sha512": "799331ce263662a4aaea750d02ffa370b63986df1f7cbd2254fb774c43b977bd26399422a9c7a95143e571fa3c56bf466050c40ea29cab1dbea29057652d7d71",
          "sha256": "3a8a023cfd4bbd872908d2ac539db50266e49748f75dd998b66e7672df1f0b43",
          "sha1": "d1becf19d8aee77d31c0aa2920445f386028dcef",
          "md5": "ea83d6b89724fe63b60953f6149efaa5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.joom.grip",
          "module": "grip",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.26.0-GA"
          }
        }
      ],
      "files": [
        {
          "name": "component-plugin-1.9.4.jar",
          "url": "component-plugin-1.9.4.jar",
          "size": 42485,
          "sha512": "799331ce263662a4aaea750d02ffa370b63986df1f7cbd2254fb774c43b977bd26399422a9c7a95143e571fa3c56bf466050c40ea29cab1dbea29057652d7d71",
          "sha256": "3a8a023cfd4bbd872908d2ac539db50266e49748f75dd998b66e7672df1f0b43",
          "sha1": "d1becf19d8aee77d31c0aa2920445f386028dcef",
          "md5": "ea83d6b89724fe63b60953f6149efaa5"
        }
      ]
    }
  ]
}
