{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.component",
    "module": "component-plugin",
    "version": "1.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "component-plugin-1.9.4.jar",
          "url": "component-plugin-1.9.4.jar",
          "size": 48286,
          "sha512": "ed13303c1581e55d74397ffa7449b811716a9a56e5b167aec42b41748435123aa1b4fff1a12de549ef7fda50ae44cd4d59609d3da4eec1295741cf5bbfa1a552",
          "sha256": "b0600d0e59ae71036cfb96d00a4ac8eec82906cdb7c1bea29e74071178239f11",
          "sha1": "feedbfc8861e983f72aa3b9bf34628869730e85a",
          "md5": "470b3c05e3f9a17f366fb6236313c42c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.joom.grip",
          "module": "grip",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.26.0-GA"
          }
        }
      ],
      "files": [
        {
          "name": "component-plugin-1.9.4.jar",
          "url": "component-plugin-1.9.4.jar",
          "size": 48286,
          "sha512": "ed13303c1581e55d74397ffa7449b811716a9a56e5b167aec42b41748435123aa1b4fff1a12de549ef7fda50ae44cd4d59609d3da4eec1295741cf5bbfa1a552",
          "sha256": "b0600d0e59ae71036cfb96d00a4ac8eec82906cdb7c1bea29e74071178239f11",
          "sha1": "feedbfc8861e983f72aa3b9bf34628869730e85a",
          "md5": "470b3c05e3f9a17f366fb6236313c42c"
        }
      ]
    }
  ]
}
