{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.component",
    "module": "component-plugin",
    "version": "1.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "component-plugin-1.9.3.jar",
          "url": "component-plugin-1.9.3.jar",
          "size": 55384,
          "sha512": "7e451ce43b53d01f912a8e0f715ac96146ce4ae384a58c11ad3bd70fe3a28ffd005d7273aee0616d3253a5464abe1436ff5ea199937a5d1dea27e7f8c432241b",
          "sha256": "c3a44e9bf857131dab1b123e0840b752e48a48919141c44ea220aba8c4d9d4c6",
          "sha1": "953d2bfd9b98f596976df65f9a97e8055c50a033",
          "md5": "0a591fcb66d1c8383a4ca589f84b2df3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.joom.grip",
          "module": "grip",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.26.0-GA"
          }
        }
      ],
      "files": [
        {
          "name": "component-plugin-1.9.3.jar",
          "url": "component-plugin-1.9.3.jar",
          "size": 55384,
          "sha512": "7e451ce43b53d01f912a8e0f715ac96146ce4ae384a58c11ad3bd70fe3a28ffd005d7273aee0616d3253a5464abe1436ff5ea199937a5d1dea27e7f8c432241b",
          "sha256": "c3a44e9bf857131dab1b123e0840b752e48a48919141c44ea220aba8c4d9d4c6",
          "sha1": "953d2bfd9b98f596976df65f9a97e8055c50a033",
          "md5": "0a591fcb66d1c8383a4ca589f84b2df3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "component-plugin-1.9.3-sources.jar",
          "url": "component-plugin-1.9.3-sources.jar",
          "size": 16907,
          "sha512": "2b4c37fe1db40e9e3c4443eb732a8a83dfad1f878c347ab56d9d1397698a1425df6e9a2455609f3bd1b300a409e717b7a84f436b251601aea282aa0e8e411ba8",
          "sha256": "7f53e1beae77fdf7027d94a24d5128949619bb5920ddea49ee3b0b59d6dbafee",
          "sha1": "e08ba300f7847b8433df66985348bcbe361500f4",
          "md5": "be87072d32707aa016a39bab8e8d71cb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "component-plugin-1.9.3-javadoc.jar",
          "url": "component-plugin-1.9.3-javadoc.jar",
          "size": 117040,
          "sha512": "1c0e8f0f93fb464036fc8a069511532a3ec295d7be25894cbb790ff60f94109d67eaecc789d0834c61453e2dc8cc2923d935d682df4b15b7eaab9cc558621cc9",
          "sha256": "7bc0035a36684038bfacb5dba901f4e1dd67a79ba8e2000a6853a58ee27ca8e4",
          "sha1": "7ee15ef0230fae593699377bb7f85cd9e2f7cf94",
          "md5": "d1ee9f22d8fc1272a29f19db2f5afd63"
        }
      ]
    }
  ]
}
