{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.component",
    "module": "component-plugin",
    "version": "1.9.5-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "component-plugin-1.9.5-rc1.jar",
          "url": "component-plugin-1.9.5-rc1.jar",
          "size": 48286,
          "sha512": "f44245524425556dae365dac77b08f1afc3f0800f9b6585e8856741a2fbb4d03455d483d9398b236b55c865ef8e89fbca58f0fc2478e29f804208d7f4ee3deb8",
          "sha256": "4d0fe039987a4fdbeb1a0bb093ac109483f21fcdeac003b1ec0778c8db84f4aa",
          "sha1": "81518054bdf59e09e19438d79e9ed32d30e90d42",
          "md5": "fbda71680bc46d322d90e333ef7afdb3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.joom.grip",
          "module": "grip",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.26.0-GA"
          }
        }
      ],
      "files": [
        {
          "name": "component-plugin-1.9.5-rc1.jar",
          "url": "component-plugin-1.9.5-rc1.jar",
          "size": 48286,
          "sha512": "f44245524425556dae365dac77b08f1afc3f0800f9b6585e8856741a2fbb4d03455d483d9398b236b55c865ef8e89fbca58f0fc2478e29f804208d7f4ee3deb8",
          "sha256": "4d0fe039987a4fdbeb1a0bb093ac109483f21fcdeac003b1ec0778c8db84f4aa",
          "sha1": "81518054bdf59e09e19438d79e9ed32d30e90d42",
          "md5": "fbda71680bc46d322d90e333ef7afdb3"
        }
      ]
    }
  ]
}
