{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.component",
    "module": "component-plugin",
    "version": "1.9.2.2-incremental1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "component-plugin-1.9.2.2-incremental1.jar",
          "url": "component-plugin-1.9.2.2-incremental1.jar",
          "size": 25728,
          "sha512": "325fc9e0f4a9aaa3b0ca02bedba97bea6c8fc74326ce841d66cc13061129f57ebc147e9f8abcbcf2bbbea4c479527bfa04b38134bbba992bbea290284cb6e76f",
          "sha256": "93a2e6f741ddf2c7634b9f8e38df6f0ea087657c75795662d63f146ea194afaa",
          "sha1": "71075f766babe3be9b4cfc98258056d42d1b26c1",
          "md5": "4787fa5942490979c273e2dbe1a94e85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-all",
          "version": {
            "requires": "5.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "component-plugin-1.9.2.2-incremental1.jar",
          "url": "component-plugin-1.9.2.2-incremental1.jar",
          "size": 25728,
          "sha512": "325fc9e0f4a9aaa3b0ca02bedba97bea6c8fc74326ce841d66cc13061129f57ebc147e9f8abcbcf2bbbea4c479527bfa04b38134bbba992bbea290284cb6e76f",
          "sha256": "93a2e6f741ddf2c7634b9f8e38df6f0ea087657c75795662d63f146ea194afaa",
          "sha1": "71075f766babe3be9b4cfc98258056d42d1b26c1",
          "md5": "4787fa5942490979c273e2dbe1a94e85"
        }
      ]
    }
  ]
}
